import type {Metadata} from "next";
import {Geist, Geist_Mono, Bodoni_Moda_SC, Gowun_Batang, Noto_Sans_KR} from "next/font/google";
import "../styles/globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const bodoniSC = Bodoni_Moda_SC({
    variable: "--font-bodoni-sc",
    subsets: ["latin"],
});

const gowunBatang = Gowun_Batang({
    subsets: ["latin"],
    weight: ["400"],
    variable: "--font-gowun-batang",
});

const notoSansKr = Noto_Sans_KR({
    variable: "--font-noto-sans-kr",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="ko">
        <body
            className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${bodoniSC.variable}
          ${gowunBatang.variable}
          ${notoSansKr.variable}
          antialiased
        `}
        >
        {children}
        </body>
        </html>
    );
}