import type {Metadata} from "next";
import {Geist, Geist_Mono, Bodoni_Moda_SC} from "next/font/google";
import "../styles/globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const bodoniSC = Bodoni_Moda_SC({
    subsets: ["latin"],
    variable: "--font-bodoni-sc",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="ko">
        <body
            className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${bodoniSC.variable}
          antialiased
        `}
        >
        {children}
        </body>
        </html>
    );
}